infra/admin_panel/admin_panel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('azucafe.urls')),
    path('azucafe/admin/', admin.site.urls),
]

handler404 = 'azucafe.views_error.page_not_found'
handler403 = 'azucafe.views_error.permission_denied'
handler500 = 'azucafe.views_error.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

infra/admin_panel/azucafe/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import cafe_detail, cafe_list, cafe_seats, cancel_reservation
from .views_booking import booking_create, booking_update
from .views_payments import payment_fail, payment_result, payment_success

app_name = 'azucafe'

urlpatterns = [
    path(
        'azucafe/cancel_reservation/<int:reservation_id>/',
        cancel_reservation,
        name='cancel_reservation',
    ),
    path('azucafe/profile/', cafe_list, name='cafe_list'),
    path(
        'azucafe/cafe_detail/<int:cafe_id>/', cafe_detail, name='cafe_detail'
    ),
    path('azucafe/cafe_seats/<int:cafe_id>/', cafe_seats, name='cafe_seats'),
    path(
        '',
        LoginView.as_view(template_name='azucafe/index.html'),
        name='index',
    ),
    path(
        'azucafe/logout/',
        LogoutView.as_view(template_name='azucafe/logged_out.html'),
        name='logout',
    ),
    path(
        'azucafe/login/',
        LoginView.as_view(template_name='azucafe/index.html'),
        name='login',
    ),
    path('azucafe/booking/', booking_create, name='booking_create'),
    path(
        'azucafe/booking/<order_id>/edit/',
        booking_update,
        name='booking_update',
    ),
    path(
        'azucafe/payresult/',
        payment_result,
        name='payment_result',
    ),
    path(
        'azucafe/paysuccess/',
        payment_success,
        name='payment_success',
    ),
    path(
        'azucafe/payfail/',
        payment_fail,
        name='payment_fail',
    ),
]

infra/admin_panel/azucafe/models.py
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class Cafe(models.Model):
    name = models.CharField(
        max_length=50, unique=True, null=False, verbose_name='Название кафе'
    )
    description = models.TextField(verbose_name='Описание кафе')
    phone = models.CharField(
        max_length=20, null=False, blank=False, verbose_name='Телефон'
    )
    address = models.CharField(
        max_length=200, null=False, verbose_name='Адрес кафе'
    )
    map_link = models.URLField(verbose_name='Ссылка на карту')
    picture = models.ImageField(
        upload_to='cafe/', blank=True, verbose_name='Картинка'
    )

    class Meta:
        verbose_name_plural = 'Кафе'
        verbose_name = 'Кафе'

    def __str__(self):
        return f'Кафе {self.name}'


class Table(models.Model):
    cafe = models.ForeignKey(
        Cafe,
        on_delete=models.CASCADE,
        to_field='id',
        verbose_name='Кафе',
    )
    table_number = models.PositiveIntegerField(
        verbose_name='Номер стола',
        null=False,
        blank=False,
        default=1,
    )
    seats_count = models.PositiveIntegerField(
        verbose_name='Посадочные места',
        null=False,
        blank=False,
        default=1,
        validators=[
            MinValueValidator(
                1,
                'Время приготовления должно быть больше или равно 1',
            )
        ],
    )
    available = models.BooleanField(
        verbose_name='Доступность',
        help_text='Доступность стола для бронирования',
        default=True,
        null=False,
        blank=False,
    )
    description = models.TextField(
        null=False, blank=True, verbose_name='Описание стола'
    )

    class Meta:
        verbose_name_plural = 'Столы'
        verbose_name = 'Стол'
        constraints = (
            models.UniqueConstraint(
                fields=('cafe', 'table_number'),
                name='table_cafe_table_number_unique',
            ),
        )

    def __str__(self):
        return (
            f'{self.cafe} Стол № {self.table_number} '
            f'({self.seats_count} '
            f'мест)'
        )


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        null=False,
        unique=True,
        verbose_name='Название категории',
    )
    description = models.TextField(
        null=False, blank=True, verbose_name='Описание категории'
    )

    class Meta:
        verbose_name_plural = 'Категории сетов'
        verbose_name = 'Категория сетов'

    def __str__(self):
        return f'Категория {self.name}'


class Set(models.Model):
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        to_field='id',
        verbose_name='Категория сета',
    )
    name = models.CharField(
        max_length=50,
        null=False,
        unique=True,
        verbose_name='Название сета',
    )
    description = models.TextField(
        null=False, blank=True, verbose_name='Описание сета'
    )
    picture = models.ImageField(
        upload_to='sets/', blank=True, verbose_name='Картинка'
    )
    cost = models.PositiveIntegerField(
        default=1,
        null=False,
        blank=False,
        verbose_name='Стоимость сета',
        validators=[
            MinValueValidator(
                1,
                'Время приготовления должно быть больше или равно 1',
            )
        ],
    )

    class Meta:
        verbose_name_plural = 'Сеты'
        verbose_name = 'Сет'

    def __str__(self):
        return f'Сет {self.name} {self.cost} руб.'


class User(models.Model):
    telegram_id = models.CharField(
        default='1',
        max_length=200,
        null=False,
        verbose_name='Телеграмм ID покупателя',
    )
    name = models.CharField(
        null=False,
        blank=True,
        max_length=1000,
        verbose_name='Имя покупателя',
    )
    phone_number = models.CharField(
        null=False, blank=False, max_length=12, verbose_name='Телефон'
    )
    admin = models.BooleanField(
        default=False,
        verbose_name='Администратор?',
    )
    superuser = models.BooleanField(
        default=False,
        verbose_name='Супер пользователь?',
    )

    class Meta:
        verbose_name_plural = 'Покупатели'
        verbose_name = 'Покупатель'

    def __str__(self):
        return f'{self.telegram_id} ({self.name})'


class Order(models.Model):
    buyer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_column='buyer_id',
        verbose_name='Покупатель',
    )
    date = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
        verbose_name='Дата создания бронирования',
    )
    from_date = models.DateTimeField(
        null=False, blank=False, verbose_name='Дата начала бронирования'
    )
    to_date = models.DateTimeField(
        null=False, blank=False, verbose_name='Дата окончания бронирования'
    )
    guests = models.PositiveIntegerField(
        default=1,
        verbose_name='Количество гостей',
        validators=[
            MinValueValidator(
                1,
                'Время приготовления должно быть больше или равно 1',
            )
        ],
    )
    cafe = models.ForeignKey(
        Cafe,
        on_delete=models.CASCADE,
        verbose_name='Кафе',
    )
    is_paid = models.BooleanField(
        default=False,
        verbose_name='Оплачено?',
    )
    is_cancelled = models.BooleanField(
        default=False,
        verbose_name='Отменено?',
    )
    description = models.TextField(
        null=False, blank=True, verbose_name='Комментарии'
    )
    admin_booking = models.BooleanField(
        default=False,
    )

    class Meta:
        verbose_name_plural = 'Бронирования'
        verbose_name = 'Бронирование'

    def __str__(self):
        return f'{self.from_date} на {self.guests} гостей'


class Booking(models.Model):
    table = models.ForeignKey(
        Table, on_delete=models.CASCADE, verbose_name='Стол'
    )
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, verbose_name='Заказ (бронь)'
    )

    class Meta:
        verbose_name_plural = 'Бронирование столов'
        verbose_name = 'Бронирование стола'

    def __str__(self):
        return (
            f'Заказ (бронь) № {self.order.id} стол '
            f'№ {self.table.table_number}'
        )


class Menu(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, verbose_name='Заказ (бронь)'
    )
    set = models.ForeignKey(Set, on_delete=models.CASCADE, verbose_name='Сет')
    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name='Количество',
        validators=[
            MinValueValidator(
                1,
                'Время приготовления должно быть больше или равно 1',
            )
        ],
    )

    class Meta:
        verbose_name_plural = 'Меню'
        verbose_name = 'Меню'

    def __str__(self):
        return (
            f'Заказ (бронь) № {self.order.id} сет '
            f'№ {self.set} {self.quantity} шт.'
        )


class Job(models.Model):
    name = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Название',
    )
    chat_id = models.BigIntegerField(
        default=1,
    )
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name='job'
    )
    data = models.TextField()
    scheduled_time = models.DateTimeField(
        null=False, blank=False, verbose_name='Дата начала бронирования'
    )
    remind_show = models.BooleanField(
        default=False,
    )


class Payment(models.Model):
    chat_id = models.BigIntegerField(
        default=1,
    )
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name='payment'
    )
    payment_link = models.TextField()
    payment_start = models.DateTimeField(
        null=False, blank=False, verbose_name='Дата начала оплаты'
    )
    payment_message_id = models.PositiveIntegerField(
        default=1,
        verbose_name='ID сообщения об оплате',
    )

infra/admin_panel/templates/payments/payment_base.html
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    {% load static %}
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <body id="background-color">
    <header>
      {% include 'payments/payment_header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
        {% endblock %}
      </div>
    </main>
    <footer>
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html>

infra/admin_panel/templates/payments/payment_fail.html
{% extends 'payments/payment_base.html' %}
{% load static %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-2">
        <img 
            src="{% static 'img/red_cross.png'%}"
            width="200px"
            height="200px"
            class="rounded-circle"
        >
    </div>
    <div class="col-md-8">
        <h2 style="color:red">Во время оплаты произошла ошибка.</h2>
        <p>Вернитесь в <a href="{{ bot_address }}">Telegram</a> и повторите оплату.</p>
        {% if order %}
            {% include 'payments/payment_order_detail.html' with order=order %}
        {% endif %}
    </div>
</div>
{% endblock %}

infra/admin_panel/templates/payments/payment_header.html
{% load static %}
<nav class="navbar navbar-light" id="background-color-header">
    <div class="container">
        <div class="row">
            <div class="col-3">
                <img src="{% static 'img/azu_logo.png'%}" width="60px" height="60px" class="rounded-circle">
            </div>
            <div class="col-9">
                <div class="admin-panel-text text-white">Кафе АЗУ</div>
                <hr class="my-2 border-white" style="width: 100%; margin: 0 auto;">
                <div class="admin-panel-text text-white">Кафе татарской кухни</div>
            </div>
        </div>
    </div>
</nav>

infra/admin_panel/templates/payments/payment_order_detail.html
<div class="mt-4">
    <h3>Детали заказа</h3>
    <p>Номер бронирования: <span class="fw-bold">{{ order.id }}</span></p>
    <p>Кафе: <span class="fw-bold">{{ order.cafe.name }}</span> ({{ order.cafe.address }})</p>
    <p>Дата: <span class="fw-bold">{{ order.from_date|date:"d.m.Y (l)" }}</span></p>
    <p>Состав заказа:</p>
    <div class="row">
        <div class="col-1"></div>
        <div class="col-11">
            {% for menu in order.menu_set.all %}
                <p>{{ menu.set.name }} - {{ menu.quantity }} шт.</p>
            {% endfor %}
        </div>
    </div>

</div>

infra/admin_panel/templates/payments/payment_success.html
{% extends 'payments/payment_base.html' %}
{% load static %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-2">
        <img 
            src="{% static 'img/green_check_mark.png'%}"
            width="200px"
            height="200px"
            class="rounded-circle"
        >
    </div>
    <div class="col-md-8">
        <h2>Оплата прошла успешно.</h2>
        <p>Через 1-2 минуты информация об оплате обноситься в Telegram-боте</p>
        <p>Для возврата в Telegram нажмите <a href="{{ bot_address }}">здесь</a></p>
        {% include 'payments/payment_order_detail.html' with order=order %}
    </div>
</div>
{% endblock %}