admin_panel/admin_panel/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('azucafe.urls')),
    path('azucafe/admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin_panel/azucafe/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import cafe_list, cafe_detail, cafe_seats, cancel_reservation
from .views_booking import booking_create, booking_update
from .views_payments import payment_result, payment_success, payment_fail

app_name = 'azucafe'

urlpatterns = [
    path('azucafe/cancel_reservation/<int:reservation_id>/', cancel_reservation, name='cancel_reservation'),
    path('azucafe/profile/', cafe_list, name='cafe_list'),
    path('azucafe/cafe_detail/<int:cafe_id>/', cafe_detail, name='cafe_detail'),
    path('azucafe/cafe_seats/<int:cafe_id>/', cafe_seats, name='cafe_seats'),
    path(
            '',
            LoginView.as_view(template_name='azucafe/index.html'),
            name='index',
        ),
    path(
            'azucafe/logout/',
            LogoutView.as_view(template_name='azucafe/logged_out.html'),
            name='logout',
        ),
    path(
            'azucafe/login/',
            LoginView.as_view(template_name='azucafe/index.html'),
            name='login',
        ),
    path(
        'azucafe/booking/',
        booking_create,
        name='booking_create'
        ),
    path(
        'azucafe/booking/<order_id>/edit/',
        booking_update,
        name='booking_update'
    ),
    path(
        'azucafe/payresult/',
        payment_result,
        name='payment_result',
    ),
    path(
        'azucafe/paysuccess/',
        payment_success,
        name='payment_success',
    ),
    path(
        'azucafe/payfail/',
        payment_fail,
        name='payment_fail',
    )
]

admin_panel/templates/includes/header.html
{% load static %}
<nav class="navbar navbar-light" id="background-color-header">
  <div class="container">
    <div class="links-container">
      <a href="{% url 'azucafe:login' %}" class="admin-info">
        <div class="admin-panel-text text-white">Кафе АЗУ</div>
      </a>
      <hr class="my-2 border-white" style="width: 100%; margin: 0 auto;">
      <a href="{% url 'azucafe:cafe_list' %}" class="admin-info">
        <div class="admin-panel-text text-white">Панель администратора</div>
      </a>
    </div>
    {% if user.is_authenticated %}
      <div class="logout-button-wrapper" style="background-color: rgba(220, 81, 50, 1); border-radius: 10px; padding: 5px 3px;">
        <a class="nav-link link-light" href="{% url 'azucafe:logout' %}">Выйти</a>
      </div>
    {% endif %}
  </div>
</nav>