infra/admin_panel/admin_panel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('azucafe.urls')),
    path('azucafe/admin/', admin.site.urls),
]

handler404 = 'azucafe.views_error.page_not_found'
handler403 = 'azucafe.views_error.permission_denied'
handler500 = 'azucafe.views_error.server_error'

if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

infra/admin_panel/azucafe/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from .views import cafe_detail, cafe_list, cafe_seats, cancel_reservation
from .views_booking import booking_create, booking_update
from .views_payments import payment_fail, payment_result, payment_success

app_name = 'azucafe'

urlpatterns = [
    path(
        'azucafe/cancel_reservation/<int:reservation_id>/',
        cancel_reservation,
        name='cancel_reservation',
    ),
    path('azucafe/profile/', cafe_list, name='cafe_list'),
    path(
        'azucafe/cafe_detail/<int:cafe_id>/', cafe_detail, name='cafe_detail'
    ),
    path('azucafe/cafe_seats/<int:cafe_id>/', cafe_seats, name='cafe_seats'),
    path(
        '',
        LoginView.as_view(template_name='azucafe/index.html'),
        name='index',
    ),
    path(
        'azucafe/logout/',
        LogoutView.as_view(template_name='azucafe/logged_out.html'),
        name='logout',
    ),
    path(
        'azucafe/login/',
        LoginView.as_view(template_name='azucafe/index.html'),
        name='login',
    ),
    path('azucafe/booking/', booking_create, name='booking_create'),
    path(
        'azucafe/booking/<order_id>/edit/',
        booking_update,
        name='booking_update',
    ),
    path(
        'azucafe/payresult/',
        payment_result,
        name='payment_result',
    ),
    path(
        'azucafe/paysuccess/',
        payment_success,
        name='payment_success',
    ),
    path(
        'azucafe/payfail/',
        payment_fail,
        name='payment_fail',
    ),
]

infra/admin_panel/azucafe/models.py
from django.core.validators import MinValueValidator
from django.db import models


# Create your models here.
class Cafe(models.Model):
    name = models.CharField(
        max_length=50, unique=True, null=False, verbose_name='Название кафе'
    )
    description = models.TextField(verbose_name='Описание кафе')
    phone = models.CharField(
        max_length=20, null=False, blank=False, verbose_name='Телефон'
    )
    address = models.CharField(
        max_length=200, null=False, verbose_name='Адрес кафе'
    )
    map_link = models.URLField(verbose_name='Ссылка на карту')
    picture = models.ImageField(
        upload_to='cafe/', blank=True, verbose_name='Картинка'
    )

    class Meta:
        verbose_name_plural = 'Кафе'
        verbose_name = 'Кафе'

    def __str__(self):
        return f'Кафе {self.name}'


class Table(models.Model):
    cafe = models.ForeignKey(
        Cafe,
        on_delete=models.CASCADE,
        to_field='id',
        verbose_name='Кафе',
    )
    table_number = models.PositiveIntegerField(
        verbose_name='Номер стола',
        null=False,
        blank=False,
        default=1,
    )
    seats_count = models.PositiveIntegerField(
        verbose_name='Посадочные места',
        null=False,
        blank=False,
        default=1,
        validators=[
            MinValueValidator(
                1,
                'Время приготовления должно быть больше или равно 1',
            )
        ],
    )
    available = models.BooleanField(
        verbose_name='Доступность',
        help_text='Доступность стола для бронирования',
        default=True,
        null=False,
        blank=False,
    )
    description = models.TextField(
        null=False, blank=True, verbose_name='Описание стола'
    )

    class Meta:
        verbose_name_plural = 'Столы'
        verbose_name = 'Стол'
        constraints = (
            models.UniqueConstraint(
                fields=('cafe', 'table_number'),
                name='table_cafe_table_number_unique',
            ),
        )

    def __str__(self):
        return (
            f'{self.cafe} Стол № {self.table_number} '
            f'({self.seats_count} '
            f'мест)'
        )


class Category(models.Model):
    name = models.CharField(
        max_length=50,
        null=False,
        unique=True,
        verbose_name='Название категории',
    )
    description = models.TextField(
        null=False, blank=True, verbose_name='Описание категории'
    )

    class Meta:
        verbose_name_plural = 'Категории сетов'
        verbose_name = 'Категория сетов'

    def __str__(self):
        return f'Категория {self.name}'


class Set(models.Model):
    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
        to_field='id',
        verbose_name='Категория сета',
    )
    name = models.CharField(
        max_length=50,
        null=False,
        unique=True,
        verbose_name='Название сета',
    )
    description = models.TextField(
        null=False, blank=True, verbose_name='Описание сета'
    )
    picture = models.ImageField(
        upload_to='sets/', blank=True, verbose_name='Картинка'
    )
    cost = models.PositiveIntegerField(
        default=1,
        null=False,
        blank=False,
        verbose_name='Стоимость сета',
        validators=[
            MinValueValidator(
                1,
                'Время приготовления должно быть больше или равно 1',
            )
        ],
    )

    class Meta:
        verbose_name_plural = 'Сеты'
        verbose_name = 'Сет'

    def __str__(self):
        return f'Сет {self.name} {self.cost} руб.'


class User(models.Model):
    telegram_id = models.CharField(
        default='1',
        max_length=200,
        null=False,
        verbose_name='Телеграмм ID покупателя',
    )
    name = models.CharField(
        null=False,
        blank=True,
        max_length=1000,
        verbose_name='Имя покупателя',
    )
    phone_number = models.CharField(
        null=False, blank=False, max_length=12, verbose_name='Телефон'
    )
    admin = models.BooleanField(
        default=False,
        verbose_name='Администратор?',
    )
    superuser = models.BooleanField(
        default=False,
        verbose_name='Супер пользователь?',
    )

    class Meta:
        verbose_name_plural = 'Покупатели'
        verbose_name = 'Покупатель'

    def __str__(self):
        return f'{self.telegram_id} ({self.name})'


class Order(models.Model):
    buyer = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        db_column='buyer_id',
        verbose_name='Покупатель',
    )
    date = models.DateTimeField(
        auto_now_add=True,
        null=False,
        blank=False,
        verbose_name='Дата создания бронирования',
    )
    from_date = models.DateTimeField(
        null=False, blank=False, verbose_name='Дата начала бронирования'
    )
    to_date = models.DateTimeField(
        null=False, blank=False, verbose_name='Дата окончания бронирования'
    )
    guests = models.PositiveIntegerField(
        default=1,
        verbose_name='Количество гостей',
        validators=[
            MinValueValidator(
                1,
                'Время приготовления должно быть больше или равно 1',
            )
        ],
    )
    cafe = models.ForeignKey(
        Cafe,
        on_delete=models.CASCADE,
        verbose_name='Кафе',
    )
    is_paid = models.BooleanField(
        default=False,
        verbose_name='Оплачено?',
    )
    is_cancelled = models.BooleanField(
        default=False,
        verbose_name='Отменено?',
    )
    description = models.TextField(
        null=False, blank=True, verbose_name='Комментарии'
    )
    admin_booking = models.BooleanField(
        default=False,
    )

    class Meta:
        verbose_name_plural = 'Бронирования'
        verbose_name = 'Бронирование'

    def __str__(self):
        return f'{self.from_date} на {self.guests} гостей'


class Booking(models.Model):
    table = models.ForeignKey(
        Table, on_delete=models.CASCADE, verbose_name='Стол'
    )
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, verbose_name='Заказ (бронь)'
    )

    class Meta:
        verbose_name_plural = 'Бронирование столов'
        verbose_name = 'Бронирование стола'

    def __str__(self):
        return (
            f'Заказ (бронь) № {self.order.id} стол '
            f'№ {self.table.table_number}'
        )


class Menu(models.Model):
    order = models.ForeignKey(
        Order, on_delete=models.CASCADE, verbose_name='Заказ (бронь)'
    )
    set = models.ForeignKey(Set, on_delete=models.CASCADE, verbose_name='Сет')
    quantity = models.PositiveIntegerField(
        default=1,
        verbose_name='Количество',
        validators=[
            MinValueValidator(
                1,
                'Время приготовления должно быть больше или равно 1',
            )
        ],
    )

    class Meta:
        verbose_name_plural = 'Меню'
        verbose_name = 'Меню'

    def __str__(self):
        return (
            f'Заказ (бронь) № {self.order.id} сет '
            f'№ {self.set} {self.quantity} шт.'
        )


class Job(models.Model):
    name = models.CharField(
        max_length=50,
        blank=False,
        null=False,
        unique=True,
        verbose_name='Название',
    )
    chat_id = models.BigIntegerField(
        default=1,
    )
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name='job'
    )
    data = models.TextField()
    scheduled_time = models.DateTimeField(
        null=False, blank=False, verbose_name='Дата начала бронирования'
    )
    remind_show = models.BooleanField(
        default=False,
    )


class Payment(models.Model):
    chat_id = models.BigIntegerField(
        default=1,
    )
    order = models.OneToOneField(
        Order, on_delete=models.CASCADE, related_name='payment'
    )
    payment_link = models.TextField()
    payment_start = models.DateTimeField(
        null=False, blank=False, verbose_name='Дата начала оплаты'
    )
    payment_message_id = models.PositiveIntegerField(
        default=1,
        verbose_name='ID сообщения об оплате',
    )

infra/admin_panel/azucafe/views.py
from datetime import date, datetime

from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render

from .constants import RAMADAN_END, RAMADAN_START
from .models import Cafe, Menu, Order, Table


def get_selected_date_and_orders(request, cafe_id):
    """Получение даты и заказов."""
    selected_date_str = request.GET.get('date')
    today = date.today()
    if selected_date_str:
        selected_date = datetime.strptime(selected_date_str, "%Y-%m-%d").date()
    else:
        if today <= RAMADAN_START:
            selected_date = RAMADAN_START
        elif today <= RAMADAN_END:
            selected_date = today
        else:
            selected_date = RAMADAN_END
    cafe = Cafe.objects.get(id=cafe_id)
    orders_for_date = Order.objects.filter(
        cafe=cafe,
        from_date__lte=selected_date,
        to_date__gte=selected_date,
        is_cancelled=False,
    )
    return selected_date, orders_for_date


def cancel_reservation(request, reservation_id):
    """Отмена бронирования."""
    reservation = get_object_or_404(Order, id=reservation_id)
    reservation.is_cancelled = True
    if hasattr(reservation, 'job'):
        reservation.job.delete()
    reservation.save()
    return redirect('azucafe:cafe_detail', cafe_id=reservation.cafe.id)


@login_required
def cafe_list(request):
    """Вывод списка кафе."""
    cafes = Cafe.objects.all()
    context = {'cafes': cafes}
    return render(request, 'azucafe/profile.html', context)


@login_required
def cafe_detail(request, cafe_id):
    """Вывод списка кафе и даты в деталях."""
    default_date = get_selected_date_and_orders(request, cafe_id)[0]
    cafes = Cafe.objects.all()
    context = {
        'cafes': cafes,
        'cafe_id': cafe_id,
        'default_date': default_date.strftime("%Y-%m-%d"),
    }
    return render(request, 'azucafe/cafe_detail.html', context)


def cafe_seats(request, cafe_id):
    """Вывод свободных мест и бронирований."""
    selected_date, orders_for_date = get_selected_date_and_orders(
        request, cafe_id
    )
    cafe = Cafe.objects.get(id=cafe_id)
    tables = Table.objects.filter(cafe=cafe, available=True)
    total_seats = tables.aggregate(total_seats=Sum('seats_count'))[
        'total_seats'
    ]
    booked_seats = (
        orders_for_date.aggregate(booked_seats=Sum('guests'))['booked_seats']
        or 0
    )
    available_seats = max(total_seats - booked_seats, 0)
    ordered_sets = Menu.objects.filter(
        order__cafe=cafe,
        order__from_date__lte=selected_date,
        order__to_date__gte=selected_date,
    ).exclude(order__is_cancelled=True)
    sets_data = ordered_sets.values('set__name').annotate(
        quantity=Sum('quantity')
    )
    reservations = Order.objects.filter(
        cafe=cafe,
        from_date__lte=selected_date,
        to_date__gte=selected_date,
        is_cancelled=False,
    ).values(
        'id',
        'buyer__name',
        'buyer__phone_number',
        'guests',
        'is_paid',
        'admin_booking',
    )
    data = {
        'total_seats': total_seats,
        'available_seats': available_seats,
        'ordered_sets': list(sets_data),
        'reservations': [],
    }
    for reservation in reservations:
        reservation_id = reservation['id']
        reservation['sets'] = list(
            ordered_sets.filter(order__id=reservation_id).values(
                'set__name', 'quantity'
            )
        )
        data['reservations'].append(reservation)
    return JsonResponse(data)

infra/admin_panel/templates/azucafe/booking.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
    <div class="col-md-8 p-5">
                <form method="post"
                      action="
                      {% if is_edit %}
                        {% url 'azucafe:booking_update' order_id=order_id %}
                      {% else %}
                        {% url 'azucafe:booking_create' %}
                      {% endif %}"
                      class="text-center">
                    {% csrf_token %}
                    <div style="margin-bottom: 10px;">
                        <legend style="padding: 0 10px; background-color: #357169; color: white; border-radius: 10px;">Выберите ресторан</legend>
                        <select name="selected_cafe" style="width: 100%; border: none;">
                            {% for cafe in cafes %}
                            <option
                                    value="{{ cafe.id }}"
                                    {% if cafe.id == selected_cafe_id %}selected
                                    {% endif %}>
                                {{ cafe.name }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>
                    <div style="margin-bottom: 10px;">
                      <legend style="padding: 0 10px; background-color: #357169; color: white; border-radius: 10px;">Выберите дату и время</legend>
                      <input type="date" style="width: 100%; border: none;" name="date" value="{{ date }}"
                          min="{{ start_date }}" max="{{ end_date }}">
                    </div>
                    {% if date_indicator %}
                        <div style="color: red; margin-bottom: 10px; text-align: left;">{{ date_message }}</div>
                    {% endif %}
                    <div style="margin-bottom: 10px;">
                      <legend style="padding: 0 10px; background-color: #357169; color: white; border-radius: 10px;">Введите имя гостя</legend>
                      <input type="text" style="width: 100%; border: none;" value="{{ guest_name }}"
                               name="guest_name" placeholder="{% if guest_name %}{% else %}Введите имя гостя{% endif %}">
                    </div>
                    {% if guest_name_indicator %}
                        <div style="color: red; margin-bottom: 10px; text-align: left;">{{ guest_name_message }}</div>
                    {% endif %}
                    <div style="margin-bottom: 10px;">
                      <legend style="padding: 0 10px; background-color: #357169; color: white; border-radius: 10px;">Введите номер телефона</legend>
                      <input type="tel" style="width: 100%; border: none;" value="{{ guest_phone }}"
                               name="guest_phone" placeholder="{% if guest_phone %}{% else %}Введите номер телефона в формате +79005552233{% endif %}">
                    </div>
                    {% if guest_phone_indicator %}
                        <div style="color: red; margin-bottom: 10px; text-align: left;">{{ guest_phone_message }}</div>
                    {% endif %}
                    <div style="margin-bottom: 10px;">
                        <legend style="padding: 0 10px; background-color: #357169; color: white; border-radius: 10px;">Сеты</legend>
                        <div style="display: flex; justify-content: flex-end; margin-top: 5px; margin-bottom: 5px;">
                            <span style="font-weight: bold;">Количество</span>
                        </div>
                        {% for set_id, menu_data in menus.items %}
                            <div style="display: flex; justify-content: space-between; margin-bottom: 5px;">
                                <span style="font-weight: bold;">{{ menu_data.name }}</span>
                                <input type="number" style="border: none; width: 15%; text-align: right;" name="quantity_{{ set_id }}" value="{{ menu_data.quantity }}">
                            </div>
                        {% endfor %}
                    </div>
                    {% if sets_indicator %}
                        <div style="color: red; margin-bottom: 10px; text-align: left;">{{ sets_message }}</div>
                    {% endif %}
                    <div style="margin-bottom: 10px;">
                        <div style="margin-right: 10px; font-weight: bold; text-align: left; margin-bottom: 5px;">Комментарий</div>
                        <div>
                            <textarea name="description" style="width: 100%; border: none;" placeholder="Введите комментарий">{{ description|linebreaksbr }}</textarea>
                        </div>
                    </div>
                    <button type="submit" style="width: 100%; padding: 0 10px; background-color: #903834; color: white; border-radius: 10px; border: none; height: 35px;">
                        {% if is_edit %}
                        Изменить бронирование
                        {% else %}
                        Забронировать стол
                        {% endif %}
                    </button>
                </form>
    </div>
</div>
{% endblock %}

infra/admin_panel/templates/azucafe/index.html
{% extends "base.html" %}
{% block title %}Вход{% endblock %}

{% block content %}
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          {% if user.is_authenticated %}
            <div class="alert alert-info" role="alert" style="text-align: center;">
              <p class="m-1">Вы уже авторизованы на сайте</p>
              <p class="m-1">Для выбора кафе нажмите <a href="{% url 'azucafe:cafe_list' %}">сюда</a></p>
            </div>
          {% else %}
            <div style="text-align: center; background-color: white; color: #357169; font-weight: bold; font-size: 500%; margin-bottom: 10px;" >              
              AZU
            </div>
                {% if form.errors %}
                  {% for field in form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger">
                        {{ error|escape }}
                      </div>
                    {% endfor %}
                  {% endfor %}
                  {% for error in form.non_field_errors %}
                    <div class="alert alert-danger">
                      {{ error|escape }}
                    </div>
                  {% endfor %}
                {% endif %}
                <form method="post" action="{% url 'azucafe:login' %}">
                  {% csrf_token %}
                  <div style="margin-bottom: 10px;">
                    <div style="margin-right: 10px; font-weight: bold; text-align: left; margin-bottom: 5px;">Username</div>
                    <input type="text" name="username" autofocus class="form-control" required id="id_username">
                  </div>
                  <div style="margin-bottom: 10px;">
                    <div style="margin-right: 10px; font-weight: bold; text-align: left; margin-bottom: 5px;">Password</div>
                    <input type="password" name="password" class="form-control" required id="id_password">
                  </div>
                  <button type="submit" style="width: 50%; padding: 0 10px; background-color: #3472df; color: white; border-radius: 10px; border: none; height: 35px;">
                    Вход
                  </button>
                </form>
              </div>
          {% endif %}
        </div>
      </div>
    </div>
  </main>
{% endblock %}

infra/admin_panel/templates/azucafe/logged_out.html
{% extends "base.html" %}
{% block title %}Выход из системы{% endblock %}
{% block content %}
  <body>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div style="font-weight: bold; text-align: center; margin-bottom: 150px;">Вы вышли из системы</div>
                <a href="{% url 'azucafe:index' %}" class="btn btn-primary" style="width: 80vw; font-weight: bold; text-align: center; background-color: #903834; color: white; border: none;">На главную</a>
            </div>
          </div>
        </div>
      </div>
    </main>
  </body>
</html>
{% endblock %}

infra/admin_panel/templates/azucafe/profile.html
{% extends 'base.html' %}
{% block content %}
    {% if user.is_authenticated %}
        <script>
            window.onload = function() {
                localStorage.clear();
            };
        </script>
        <div class="text-center">
            <h2>Выберите кафе</h2>
            <div>
                <ul class="list-group">
                    {% for cafe in cafes %}
                        <li class="list-group-item" id="background-color">
                            <a class="list-group list-group-flush font-weight-bold" href="{% url 'azucafe:cafe_detail' cafe.id %}">{{ cafe.name }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div>
                <a class="btn btn-primary mt-3" href="{% url 'azucafe:booking_create' %}">Забронировать стол</a>
            </div>
        </div>
    {% endif %}
{% endblock %}